spring.application.name=e-commerce-website

# Server Port
server.port=8080

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Razorpay Config
razorpay.key_id=rzp_test_SrYaZcafVeKl6q
razorpay.key_secret=Xd3aFDCLqVY3XKiHSTC2N3qC

jwt.secret=MySuperSecretKeyForEcommerceWebsite2026JWT
jwt.access.expiration=900000
jwt.refresh.expiration=604800000

#15 minutes access token

#7 days refresh token

#30000 5 min ke liye 